---
- name: save fortigate config to a file
  hosts: fortigateCherarba
  connection: httpapi
  collections:
  - fortinet.fortios
  vars_files:
    - vars/fortigate_env_var/vars.yml
    - vars/fortigate_env_var/vault.yml
  roles:
    - role: fortigate-config-to-file
      vars:
        vdom: "root"
        save_backup_path: "/somedir/seconddir" #override the default path if you want
